### ISSUE TITLE
Fail to install embed module

### ISSUE THREAD

**Issue by PanZiwei** [adbailey4/embed_fast5#8]
Hi,
I failed to install the embed_fast5 with the github method with the following install steps.
```shell
conda create -n embed_fast5 python=3.7
conda activate embed_fast5
git clone --recursive https://github.com/adbailey4/embed_fast5.git
cd embed_fast5
pip install pytest cmake ## Need to install pytest, cmake >=3.15
python3.7 -m pip install .
python3.7 -m pytest
```
Specifically, I failed to Build the wheel of embed module, and can't run pytest later.
Do you have any suggestions on debugging?
Thank you so much for your help!

The error of the embed wheel is shown below:
```shell
Building wheels for collected packages: embed
  Building wheel for embed (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/pod/2/li-lab/Ziwei/software/embed_fast5/setup.py'"'"'; __file__='"'"'/pod/2/li-lab/Ziwei/software/embed_fast5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-zipika88
       cwd: /pod/2/li-lab/Ziwei/software/embed_fast5/
  Complete output (106 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/embed
  copying src/embed/fast5.py -> build/lib.linux-x86_64-3.7/embed
  copying src/embed/__init__.py -> build/lib.linux-x86_64-3.7/embed
  copying src/embed/split_multi_read.py -> build/lib.linux-x86_64-3.7/embed
  copying src/embed/embedding_helpers.py -> build/lib.linux-x86_64-3.7/embed
  running build_ext
  -- The C compiler identification is GNU 4.8.5
  -- The CXX compiler identification is GNU 4.8.5
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- CMakeInstall Prefix: /usr/local
  -- Finding Embed Dependencies
  --   BUILDING STATIC LIBS
  CMake Deprecation Warning at build/temp.linux-x86_64-3.7/_deps/googletest-src/CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  CMake Deprecation Warning at build/temp.linux-x86_64-3.7/_deps/googletest-src/googlemock/CMakeLists.txt:41 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  CMake Deprecation Warning at build/temp.linux-x86_64-3.7/_deps/googletest-src/googletest/CMakeLists.txt:48 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  --   Found PythonInterp: /pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/bin/python3.7 (found version "3.7.12")
  --   Looking for pthread.h
  --   Looking for pthread.h - found
  --   Performing Test CMAKE_HAVE_LIBC_PTHREAD
  --   Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  --   Looking for pthread_create in pthreads
  --   Looking for pthread_create in pthreads - not found
  --   Looking for pthread_create in pthread
  --   Looking for pthread_create in pthread - found
  --   Found Threads: TRUE
  CMake Error at /pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/site-packages/cmake/data/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find Boost: Found unsuitable version "1.53.0", but required is at
    least "1.65.1" (found /usr/include, )
  Call Stack (most recent call first):
    /pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/site-packages/cmake/data/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:592 (_FPHSA_FAILURE_MESSAGE)
    /pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/site-packages/cmake/data/share/cmake-3.22/Modules/FindBoost.cmake:2360 (find_package_handle_standard_args)
    cmake/AddDependencies.cmake:30 (find_package)
    CMakeLists.txt:29 (include)


  -- Configuring incomplete, errors occurred!
  See also "/pod/2/li-lab/Ziwei/software/embed_fast5/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
  See also "/pod/2/li-lab/Ziwei/software/embed_fast5/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/pod/2/li-lab/Ziwei/software/embed_fast5/setup.py", line 182, in <module>
      main()
    File "/pod/2/li-lab/Ziwei/software/embed_fast5/setup.py", line 174, in main
      test_suite='tests'
    File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/pod/2/li-lab/Ziwei/software/embed_fast5/setup.py", line 86, in run
      self.build_extension(ext)
    File "/pod/2/li-lab/Ziwei/software/embed_fast5/setup.py", line 115, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/pod/2/li-lab/Ziwei/software/embed_fast5', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/pod/2/li-lab/Ziwei/software/embed_fast5/build/lib.linux-x86_64-3.7/embed', '-DPYTHON_EXECUTABLE=/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/bin/python3.7', '-DBUILD_SHARED_LIBS=OFF', '-DCMAKE_VERBOSE_MAKEFILE=ON', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for embed
  Running setup.py clean for embed
Failed to build embed
Installing collected packages: future, ecdsa, cryptography, aws-sam-translator, xmltodict, werkzeug, sshpubkeys, responses, pytz, python-jose, numpy, mock, jsondiff, Jinja2, docker, cfn-lint, boto, aws-xray-sdk, threadpoolctl, scipy, pillow, moto, kiwisolver, joblib, fonttools, cycler, scikit-learn, pandas, matplotlib, pysam, py3helpers, mappy, Cython, cached-property, biopython, h5py, embed
    Running setup.py install for embed ... error
    ERROR: Command errored out with exit status 1:
     command: /pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/pod/2/li-lab/Ziwei/software/embed_fast5/setup.py'"'"'; __file__='"'"'/pod/2/li-lab/Ziwei/software/embed_fast5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7pmgc30g/install-record.txt --single-version-externally-managed --compile --install-headers /pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/include/python3.7m/embed
         cwd: /pod/2/li-lab/Ziwei/software/embed_fast5/
    Complete output (112 lines):
    running install
    /pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/embed
    copying src/embed/fast5.py -> build/lib.linux-x86_64-3.7/embed
    copying src/embed/__init__.py -> build/lib.linux-x86_64-3.7/embed
    copying src/embed/split_multi_read.py -> build/lib.linux-x86_64-3.7/embed
    copying src/embed/embedding_helpers.py -> build/lib.linux-x86_64-3.7/embed
    running build_ext
    -- The C compiler identification is GNU 4.8.5
    -- The CXX compiler identification is GNU 4.8.5
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- CMakeInstall Prefix: /usr/local
    -- Finding Embed Dependencies
    --   BUILDING STATIC LIBS
    CMake Deprecation Warning at build/temp.linux-x86_64-3.7/_deps/googletest-src/CMakeLists.txt:1 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.

      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.


    CMake Deprecation Warning at build/temp.linux-x86_64-3.7/_deps/googletest-src/googlemock/CMakeLists.txt:41 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.

      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.


    CMake Deprecation Warning at build/temp.linux-x86_64-3.7/_deps/googletest-src/googletest/CMakeLists.txt:48 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.

      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.


    --   Found PythonInterp: /pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/bin/python3.7 (found version "3.7.12")
    --   Looking for pthread.h
    --   Looking for pthread.h - found
    --   Performing Test CMAKE_HAVE_LIBC_PTHREAD
    --   Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
    --   Looking for pthread_create in pthreads
    --   Looking for pthread_create in pthreads - not found
    --   Looking for pthread_create in pthread
    --   Looking for pthread_create in pthread - found
    --   Found Threads: TRUE
    CMake Error at /pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/site-packages/cmake/data/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
      Could NOT find Boost: Found unsuitable version "1.53.0", but required is at
      least "1.65.1" (found /usr/include, )
    Call Stack (most recent call first):
      /pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/site-packages/cmake/data/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:592 (_FPHSA_FAILURE_MESSAGE)
      /pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/site-packages/cmake/data/share/cmake-3.22/Modules/FindBoost.cmake:2360 (find_package_handle_standard_args)
      cmake/AddDependencies.cmake:30 (find_package)
      CMakeLists.txt:29 (include)


    -- Configuring incomplete, errors occurred!
    See also "/pod/2/li-lab/Ziwei/software/embed_fast5/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
    See also "/pod/2/li-lab/Ziwei/software/embed_fast5/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/pod/2/li-lab/Ziwei/software/embed_fast5/setup.py", line 182, in <module>
        main()
      File "/pod/2/li-lab/Ziwei/software/embed_fast5/setup.py", line 174, in main
        test_suite='tests'
      File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/pod/2/li-lab/Ziwei/software/embed_fast5/setup.py", line 130, in run
        install.run(self)
      File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/site-packages/setuptools/command/install.py", line 68, in run
        return orig.install.run(self)
      File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/pod/2/li-lab/Ziwei/software/embed_fast5/setup.py", line 86, in run
        self.build_extension(ext)
      File "/pod/2/li-lab/Ziwei/software/embed_fast5/setup.py", line 115, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/pod/2/li-lab/Ziwei/software/embed_fast5', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/pod/2/li-lab/Ziwei/software/embed_fast5/build/lib.linux-x86_64-3.7/embed', '-DPYTHON_EXECUTABLE=/pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/bin/python3.7', '-DBUILD_SHARED_LIBS=OFF', '-DCMAKE_VERBOSE_MAKEFILE=ON', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/pod/2/li-lab/Ziwei/software/embed_fast5/setup.py'"'"'; __file__='"'"'/pod/2/li-lab/Ziwei/software/embed_fast5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7pmgc30g/install-record.txt --single-version-externally-managed --compile --install-headers /pod/2/li-lab/Ziwei/Anaconda3/envs/embed_fast5/include/python3.7m/embed Check the logs for full command output.
```

```shell
(embed_fast5) [c-panz@sumner051 embed_fast5]$ pytest
======================================================================== test session starts =========================================================================
platform linux -- Python 3.7.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /pod/2/li-lab/Ziwei/software/embed_fast5, configfile: pytest.ini, testpaths: tests
collected 1 item / 3 errors

=============================================================================== ERRORS ===============================================================================
__________________________________________________________ ERROR collecting tests/test_embedding_helpers.py __________________________________________________________
ImportError while importing test module '/pod/2/li-lab/Ziwei/software/embed_fast5/tests/test_embedding_helpers.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../Anaconda3/envs/embed_fast5/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_embedding_helpers.py:17: in <module>
    from embed.embedding_helpers import *
E   ModuleNotFoundError: No module named 'embed'
___________________________________________________________ ERROR collecting tests/test_python_wrappers.py ___________________________________________________________
ImportError while importing test module '/pod/2/li-lab/Ziwei/software/embed_fast5/tests/test_python_wrappers.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../Anaconda3/envs/embed_fast5/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_python_wrappers.py:17: in <module>
    from embed import bindings
E   ModuleNotFoundError: No module named 'embed'
__________________________________________________________ ERROR collecting tests/test_split_multi_read.py ___________________________________________________________
ImportError while importing test module '/pod/2/li-lab/Ziwei/software/embed_fast5/tests/test_split_multi_read.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../Anaconda3/envs/embed_fast5/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_split_multi_read.py:17: in <module>
    from embed.split_multi_read import *
E   ModuleNotFoundError: No module named 'embed'
====================================================================== short test summary info =======================================================================
ERROR tests/test_embedding_helpers.py
ERROR tests/test_python_wrappers.py
ERROR tests/test_split_multi_read.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================= 3 errors in 0.20s ==========================================================================
```

**Comment by adbailey4** [comment]
It looks like you have the wrong boost and CMake version installed.

What are the version numbers of the dependencies listed in the readme (Boost, HDF5, eigen, htslib, cmake)?
